language: c

branches:
  only:
    - create-ponyc-options

dist: trusty
sudo: required

matrix:
  include:

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=debug
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - FAVORITE_CONFIG=yes
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="5.0.0"
        - LLVM_CONFIG="llvm-config-5.0"
        - config=debug
        - CC1=gcc-6
        - CXX1=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="5.0.0"
        - LLVM_CONFIG="llvm-config-5.0"
        - config=release
        - CC1=gcc-6
        - CXX1=g++-6

    - os: osx
      env:
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - CC1=clang-3.9
        - CXX1=clang++-3.9

    - os: osx
      env:
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="5.0.0"
        - LLVM_CONFIG="llvm-config-5.0"
        - CC1=clang-5.0
        - CXX1=clang++-5.0


rvm:
  - 2.2.3

install:
  - bash .travis_install.bash

script:
  - bash .travis_script.bash

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
    - wink@saville.com
